import { Inter } from "next/font/google";
import BottomNav from "~/components/layout/BottomNav";
import { TopNav } from "~/components/layout/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticketer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <TopNav />
      <main className="relative top-12 pb-12">{children}</main>
      <BottomNav />
    </>
  );
}
