import { GTProviders } from "~/providers";
import "./globals.css";
import { Inter, Noto_Sans_Javanese } from "next/font/google";
import supabase from "~/lib/supabase";
import { Suspense } from "react";
import { Toaster } from "~/components/common/toater";
import { cn } from "~/lib/ui/utils";
const notoSansJp = Noto_Sans_Javanese({
  subsets: ["latin"],
});

export const metadata = {
  title: "Ticketer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await supabase.auth.getSession();
  console.log(data);
  return (
    <html lang="ja">
      <body
        className={cn("h-screen w-screen bg-primary", notoSansJp.className)}
      >
        <main className="container bg-gray-50 h-full p-8 box-border pb-24">
          <GTProviders>
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            <Toaster />
          </GTProviders>
        </main>
      </body>
    </html>
  );
}
