import { GTProviders } from "~/providers";
import "./globals.css";
import { Noto_Sans_Javanese } from "next/font/google";
import { Toaster } from "~/components/common/toater";
import { cn } from "~/lib/ui/utils";
import { getBaseUrl } from "~/util/api";
const notoSansJp = Noto_Sans_Javanese({
  subsets: ["latin"],
});

export const metadata = {
  title: "Ticketer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head>
        <meta name="application-name" content="ticketer" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="ticketer" />
        <meta name="description" content="チケット発行アプリ" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        {/* <meta name="msapplication-config" content="/icons/browserconfig.xml" /> */}
        <meta name="msapplication-TileColor" content="#2B5797" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
        />

        <link rel="apple-touch-icon" href="/icons/touch-icon-iphone.png" />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/icons/touch-icon-ipad.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/icons/touch-icon-iphone-retina.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="167x167"
          href="/icons/touch-icon-ipad-retina.png"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/icons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/icons/favicon-16x16.png"
        />
        <link rel="manifest" href="/manifest.json" />
        <link
          rel="mask-icon"
          href="/icons/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <link rel="shortcut icon" href="/favicon.ico" />

        <meta name="twitter:card" content="summary" />
        <meta name="twitter:url" content={getBaseUrl()} />
        <meta name="twitter:title" content="ticketer" />
        <meta name="twitter:description" content="チケット発行アプリ" />
        <meta name="twitter:image" content="/android-chrome-192x192.png" />
        <meta name="twitter:creator" content="@skyt" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="ticketer" />
        <meta property="og:description" content="チケット発行アプリ" />
        <meta property="og:site_name" content="ticketer" />
        <meta property="og:url" content={getBaseUrl()} />
        <meta property="og:image" content="/apple-touch-icon.png" />
        <title>ticketer</title>
      </head>
      <body
        className={cn("h-screen w-screen bg-primary", notoSansJp.className)}
      >
        <main className="container bg-gray-50 m-h-full p-8 box-border pb-24">
          <GTProviders>
            {children}
            <Toaster />
          </GTProviders>
        </main>
      </body>
    </html>
  );
}
